### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "1607b56c19ae408d93655622ed633706",
  "accountNumber" : "1000000000",
  "amount": 1000
}