### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "f65c9d373034411b83a42f7f486014ee",
  "accountNumber" : "1000000000",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/f65c9d373034411b83a42f7f486014ee